# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Tapio totem'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left"]'
      kconfig: '["CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16"]'
